
services:
  task-service:
    build: ./services/task-service
    container_name: task-service-container
    ports:
      - "3001:3001"
    env_file:
      - ./services/task-service/.env
    restart: always